config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root "root#top"

  get  "signup" => "users#new"
  post  "signup" => "users#create"
  get "tos" => "users#tos", as: :tos
  get "send_email" => "users#send_email", as: :send_email
  get "mypage/:user_id" => "users#show", as: :mypage
  get "wedding_gift/:user_id" => "users#wedding_gift", as: :wedding_gift
  resources :users, only: [:edit, :update, :destroy]

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :password_resets, only: [:new, :create, :edit, :update]

  get ":user_id/invitations/type" => "invitations#type", as: :type
  get "invitations/:id/profile" => "invitations#profile", as: :profile
  get "invitations/:id/date_place" => "invitations#date_place", as: :date_place
  get "invitations/:id/greeting" => "invitations#greeting", as: :greeting
  get "invitations/:id/preview/:design_id" => "invitations#preview", as: :preview
  get ":user_id/invitations/couple_name/:type_id" => "invitations#couple_name", as: :couple_name
  get "invitations/design/:id/:type_id" => "invitations#design", as: :design
  get "invitations/:user_id/index" => "invitations#index", as: :index
  resources :invitations, only: [:show, :update, :create, :destroy]

  get "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#show", as: :attendance_form_show
  patch "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#update", as: :attendance_form_update

  get "attendances/:atd_id/confirm" => "attendances#confirm", as: :confirm
  resources :attendances, only: [:show, :create, :update]

  get "lists/:user_id" => "lists#show", as: :list

  resources :account_activations, only: [:edit]

  get "message_cards/:id/profile" => "message_cards#profile", as: :msg_profile
  get "message_cards/:id/preview" => "message_cards#preview", as: :msg_preview
  get "message_cards/:id/greeting" => "message_cards#greeting", as: :msg_greeting
  get "message_cards/:user_id/index" => "message_cards#index", as: :msg_index
  resources :message_cards, only: [:new, :show, :update, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/message_card.rb
class MessageCard < ApplicationRecord
  belongs_to :user
end

app/controllers/message_cards_controller.rb
class MessageCardsController < ApplicationController
  before_action :logged_in_user
  before_action :ensure_correct_user, only: [:index]
  before_action :ensure_msg_card_correct_user, except: [:new, :index, :create, :update]

  def index
    @message_cards = MessageCard.where(user_id: params[:user_id]).order("created_at ASC")
  end

  def new
    @message_card = MessageCard.new
  end

  def show
    @message_card = MessageCard.find_by(id: params[:id])
  end

  def profile
    @message_card = MessageCard.find_by(id: params[:id])
  end

  def greeting
    @message_card = MessageCard.find_by(id: params[:id])
  end

  def create
    @message_card = current_user.message_cards.new(message_card_params)
    if @message_card.save
      redirect_to message_card_url(id: @message_card)
    else
      render "new"
    end
  end

  def update
    @message_card = MessageCard.find_by(id: params[:id])
    if @message_card.update_attributes(message_card_params)
      redirect_to message_card_url(@message_card)
    else
      render 'design'
    end
  end

  private

    def message_card_params
      params.require(:message_card).permit(
        :msg_design_id, :title, :date, :greeting, :public,
        :groom_last, :groom_first, :groom_last_kana, :groom_first_kana,
        :bride_last, :bride_first, :bride_last_kana, :bride_first_kana,
      )
    end
end

app/helpers/message_cards_helper.rb
module MessageCardsHelper
end

app/views/message_cards/design.html.erb
<h1>デザインの種類</h1>

<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="row">
      <div class="col-6">
        <%= link_to invitation_path(@invitation, :invitation => {design_id: 1}), method: "PATCH" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/1.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ１</p>
        </div>
        <% end %>
      </div>
      <div class="col-6">
        <%= link_to invitation_path(@invitation, :invitation => {design_id: 2}), method: "PATCH" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/2.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ２</p>
        </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <%= link_to invitation_path(@invitation, :invitation => {design_id: 3}), method: "PATCH" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/3.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ３</p>
        </div>
        <% end %>
      </div>
      <div class="col-6">
        <%= link_to invitation_path(@invitation, :invitation => {design_id: 4}), method: "PATCH" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/4.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ４</p>
        </div>
        <% end %>
      </div>
    </div>
    <div>
      <%= link_to "OK", invitations_path, class:"btn btn-sm btn-primary pl-8 pr-8" %>
    </div>
  </div>
</main>

app/views/message_cards/greeting.html.erb
<%= form_for(@message_card, url: message_card_path, method: "PATCH") do |f| %>
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="">
      <div class="text-center">
        <h2 class="mb-0" style="">挨拶文編集</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
      </div>
    </div>


    <div class="" style="">
      <!-- <%= f.label "挨拶文" %> -->
      <%= f.text_area :greeting, class:"w-50 p-2 mh-greet" %>
    </div>

    <div class="mt-2 w-50 mx-auto">
      <div class="text-left">
        <a class="btn btn-sm btn-dark text-white pl-8 pr-8">例文を選択する</a>
      </div>
    </div>

    <div class="mt-9">
      <%= f.submit "保存", class:"btn btn-sm btn-primary pl-8 pr-8" %><br>
      <%= link_to "戻る", message_card_path(id: @message_card), class:"btn btn-sm btn-secondary pl-8 pr-8 mt-4" %>
    </div>

  </div>



</main>
<% end %>

app/views/message_cards/index.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="">
      <div class="text-center">
        <h2 class="mb-0" style="">メッセージカード一覧</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
      </div>
    </div>
    <div class="row">
      <% @message_cards.each do |msg| %>
      <div class="col-3">
        <%= link_to message_card_path(id: msg.id) do %>
        <div class="m-4 mx-auto">
          <img src="/default.jpg" width="" class="w-80 mt-4">
          <p class="mt-4"><%= msg.id %></p>
        </div>
      </div>
      <% end %>
      <% end %>
      <div class="col-3">
        <%= link_to new_message_card_path do %>
        <div class="step-card invitations p-4 m-6 mx-auto">
          <img src="/mypage/card.png" width="" class="w-100  step-icon">
          <img src="/mypage/card2.png" width="" class="w-100  step-icon-hover">
          <p class="">新規作成</p>
        </div>
        <% end %>
      </div>
    </div>
    <div>
    </div>
  </div>
</main>

app/views/message_cards/new.html.erb
<h1>デザインの種類</h1>
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="row">
      <div class="col-6">
        <%= link_to message_cards_path(@message_card, :message_card => {msg_design_id: 1}), method: "POST" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/1.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ１</p>
        </div>
        <% end %>
      </div>
      <div class="col-6">
        <%= link_to message_cards_path(@message_card, :message_card => {msg_design_id: 2}), method: "POST" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/2.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ２</p>
        </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-6">
        <%= link_to message_cards_path(@message_card, :message_card => {msg_design_id: 3}), method: "POST" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/3.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ３</p>
        </div>
        <% end %>
      </div>
      <div class="col-6">
        <%= link_to message_cards_path(@message_card, :message_card => {msg_design_id: 4}), method: "POST" do %>
        <div class="step-card p-4 m-6 mx-auto">
          <img src="/step_icon/4.png" width="" class="w-50 mt-4">
          <p class="mt-4">テンプレ４</p>
        </div>
        <% end %>
      </div>
    </div>
    <div>
    </div>
  </div>
</main>

app/views/message_cards/profile.html.erb
<%= form_for(@message_card, url: message_card_path, method: "PATCH") do |f| %>
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="">
      <div class="text-center">
        <h2 class="mb-0" style="">プロフィール編集</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
      </div>
    </div>

    <div class="inv-profile">
      <h6 class="mt-8" style="font-size:2.0rem; line-height: 0.5;">新郎<br><span style="font-size:1rem;">groom</span></h6>
      <div class="row mt-4">
        <div class="groom-img col-sm-4">
          <img src="/icon/groom.png" class="w-70">
          <p class="mt-2">写真を選択する</p>
        </div>
        <div class="groom-profile text-left col-sm-8">
          <label class="ml-2">名前</label>
          <!-- <%= f.label "新郎", class:"d-block small text-left" %> -->
          <div class="overflow-hidden" style="margin:0px !important;">
            <%= f.text_field :groom_last, class:"w-49 p-2 float-left inv-card",placeholder:"  性    Last" %>
            <%= f.text_field :groom_first, class:"w-49 p-2 float-right inv-card",placeholder:"  名    First" %>
          </div>
          <label class="ml-2">かな</label>
          <!-- <%= f.label "新郎", class:"d-block small text-left" %> -->
          <div class="overflow-hidden" style="margin:0px !important;">
            <%= f.text_field :groom_last_kana, class:"w-49 p-2 float-left inv-card",placeholder:"  せい" %>
            <%= f.text_field :groom_first_kana, class:"w-49 p-2 float-right inv-card",placeholder:"  めい" %>
          </div>

          <!-- 自己紹介・メッセージ -->
          <div class="mt-4">
            <label class="ml-2">自己紹介・メッセージ</label>
            <%= f.text_area :groom_msg, class:"w-100 p-2 inv-card",placeholder:"  自己紹介や一言メッセージなどを記入して下さい" %>
          </div>
        </div>
      </div>
    </div>

    <div class="inv-profile">
      <h6 class="mt-8" style="font-size:2.0rem; line-height: 0.5;">新婦<br><span style="font-size:1rem;">bride</span></h6>
      <div class="row mt-4">
        <div class="groom-img col-sm-4">
          <img src="/icon/bride.png" class="w-70">
          <p class="mt-2">写真を選択する</p>
        </div>
        <div class="groom-profile text-left col-sm-8">
          <label class="ml-2">名前</label>
          <!-- <%= f.label "新婦", class:"d-block small text-left" %> -->
          <div class="overflow-hidden" style="margin:0px !important;">
            <%= f.text_field :bride_last, class:"w-49 p-2 float-left inv-card",placeholder:"  性    Last" %>
            <%= f.text_field :bride_first, class:"w-49 p-2 float-right inv-card",placeholder:"  名    First" %>
          </div>
          <label class="ml-2">かな</label>
          <!-- <%= f.label "新婦", class:"d-block small text-left" %> -->
          <div class="overflow-hidden" style="margin:0px !important;">
            <%= f.text_field :bride_last_kana, class:"w-49 p-2 float-left inv-card",placeholder:"  せい" %>
            <%= f.text_field :bride_first_kana, class:"w-49 p-2 float-right inv-card",placeholder:"  めい" %>
          </div>

          <!-- 自己紹介・メッセージ -->
          <div class="mt-4">
            <label class="ml-2">自己紹介・メッセージ</label>
            <%= f.text_area :bride_msg, class:"w-100 p-2 inv-card",placeholder:"  自己紹介や一言メッセージなどを記入して下さい" %>
          </div>
        </div>
      </div>
    </div>

    <div class="mt-9">
      <%= f.submit "保存", class:"btn btn-sm btn-primary pl-8 pr-8" %><br>
      <%= link_to "戻る", message_card_path(id: @message_card), class:"btn btn-sm btn-secondary pl-8 pr-8 mt-4" %>
    </div>

    <% end %>
  </div>
</main>

app/views/message_cards/show.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center w-60">
    <div class="">
      <div class="text-center">
        <h2 class="mb-0" style="">メッセージカード編集TOP</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
        <h6 class="mt-8">
          <% if @message_card.title.nil? %>
          <div class="">
            <p>
              招待状_<%= @message_card.id %>
              <!-- 切り替えボタンの設定 -->
              <a type="" class="yubi" data-toggle="modal" data-target="#exampleModalCenter">
                <img src="/icon/pencil.png" class="w-5 p-2">
              </a>
            </p>
          </div>
          <% else %>
          <div class="">
            <p>
              <%= @message_card.title %>
              <!-- 切り替えボタンの設定 -->
              <a type="" class="yubi" data-toggle="modal" data-target="#exampleModalCenter">
                <img src="/icon/pencil.png" class="w-5 p-2">
              </a>
            </p>
          </div>
          <% end %>
        </h6>

        <!-- モーダルの設定 -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title w-100" id="exampleModalCenterTitle">招待状の名前を変更する</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= form_for(@message_card, url: message_card_path, method: "PATCH") do |f| %>
                <% if @message_card.title.nil? %>
                <div class="modal-body">
                  <p><%= f.text_field :title, value: "招待状_#{@message_card.id}" %></p>
                </div>
                <% else %>
                <div class="modal-body">
                  <p><%= f.text_field :title, value: @message_card.title %></p>
                </div>
                <% end %>
                <div class="modal-footer">
                  <%= f.submit "変更を保存", class: "btn btn-sm btn-primary" %>
                  <button type="button" class="btn btn-sm btn-dark" data-dismiss="modal">閉じる</button>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="my-4 text-center">
      <% if @message_card.public == false %>
        <%= link_to message_card_path(@message_card, :message_card => {public: true}), method: "PATCH", class:"btn btn-sm btn-primary pl-8 pr-8" do %>
          公開
        <% end %>
      <% else %>
        <%= link_to message_card_path(@message_card, :message_card => {public: false}), method: "PATCH", class:"btn btn-sm btn-primary pl-8 pr-8" do %>
          非公開
        <% end %>
      <% end %>
    </div>
    <div class="mt-4 bg-img img-fit">
      <%= link_to invitations_path,class:"bg-img-padding w-100 my-auto" do %>
      <div class="amikake" style="height: 300px;background-color: rgba(0,0,0,.5);">
        <p class="text-white" style="padding-top:140px;">画像を選択する</p>
      </div>
      <% end %>
    </div>
    <div class="mt-4 m-0" style="overflow:hidden;">
      <%= link_to msg_profile_path(id: @message_card) do %>
      <div class="inv-card w-49 p-4" style="float:left;">
        <h4 class="mb-0">プロフィール</h4>
      </div>
      <% end %>
      <%= link_to msg_greeting_path(id: @message_card) do %>
      <div class="inv-card w-49 p-4" style="float:right;">
        <h4 class="mb-0">挨拶文</h4>
      </div>
      <% end %>
    </div>
    <div>
      <%= link_to "プレビュー", invitations_path, class:"btn btn-sm btn-primary pl-8 pr-8 mb-2 mt-4" %><br>
    </div>
    <div class="w-80 mt-4 m-0 overflow-hidden" style="margin-left:10% !important;">
      <div class="inv-card w-49 p-4 float-left">
        <%= link_to "https://social-plugins.line.me/lineit/share?url=#{@url}" do %>
          <h4 class="mb-0">LINEで送る</h4>
        <% end %>
      </div>
      <div class="inv-card w-49 p-4 float-right">
        <%= link_to "http://www.facebook.com/share.php?u=#{@url}" do %>
          <h4 class="mb-0">FBでシェア</h4>
        <% end %>
      </div>
    </div>
    <div class="w-80 mt-4 m-0 overflow-hidden" style="margin-left:10% !important;">
      <div class="inv-card w-49 p-4 float-left">
        <%= link_to "http://twitter.com/share?url=#{@url}" do %>
          <h4 class="mb-0">Twitterでシェア</h4>
        <% end %>
      </div>
      <div class="inv-card w-49 p-4 float-right">
        <!-- コピー対象要素とコピーボタン -->
        <input id="copyTarget" type="text" value="<%= @url %>" readonly class="invisible p-0 m-0" style="height:0; width: 0;border:none;">
        <a onclick="copyToClipboard()" class="h4 yubi">URLをコピー</a>
      </div>

    </div>
  </div>
</main>


    <!-- テキストをコピーするjs -->
    <script>
        function copyToClipboard() {
            // コピー対象をJavaScript上で変数として定義する
            var copyTarget = document.getElementById("copyTarget");
            // コピー対象のテキストを選択する
            copyTarget.select();
            // 選択しているテキストをクリップボードにコピーする
            document.execCommand("Copy");
            // コピーをお知らせする
            alert("コピーできました！ : " + copyTarget.value);
        }
    </script>

app/views/message_cards/show_old.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center w-60">
    <div class="row">
      <div class="col-4"></div>
      <div class="col-4">
        <h2 class="mb-0" style="">メッセージカード編集TOP</h2>
        <div class="w-50 step-border mb-3" style=""></div>
        <h6 class="mt-8">メッセージカード_1<span><img src="/icon/hane.png" class="w-15 p-2"></span></h6>
        <h6 class="mt-8">
          <% if @message_card.public == false %>
            <%= link_to message_card_path(@message_card, :message_card => {public: true}), method: "PATCH", class:"btn btn-sm btn-primary pl-8 pr-8" do %>
              公開
            <% end %>
          <% else %>
            <%= link_to message_card_path(@message_card, :message_card => {public: false}), method: "PATCH", class:"btn btn-sm btn-primary pl-8 pr-8" do %>
              非公開
            <% end %>
          <% end %>
        </h6>
      </div>
      <div class="col-4"></div>
    </div>
    <div class="inv-card p-4">
      <h2 class="">テンプレート選択</h2>
    </div>
    <div class="mt-4 p-9 bg-light">
      <h2 class="">画像</h2>
    </div>
    <div class="row mt-4 m-0">
      <div class="inv-card w-45 p-4 m-3">
        <h4 class="mb-0"><%= link_to "プロフィール", msg_profile_path(id: @message_card) %></h4>
      </div>
      <div class="inv-card w-45 p-4 m-3">
        <h4 class="mb-0"><%= link_to "挨拶文", msg_greeting_path(id: @message_card) %></h4>
      </div>
    </div>
    <div>
      <%= link_to "プレビュー", invitations_path, class:"btn btn-sm btn-primary pl-8 pr-8 mb-2 mt-4" %><br>
    </div>
    <div class="row mt-4 m-0">
      <div class="w-15 p-4 ">
        <h4 class="mb-0"></h4>
      </div>
      <div class="inv-card w-30 p-4 m-3">
        <h4 class="mb-0">LINEで送る</h4>
      </div>
      <div class="inv-card w-30 p-4 m-3">
        <h4 class="mb-0">FBでシェア</h4>
      </div>
    </div>
    <div class="row m-0">
      <div class="w-15 p-4">
        <h4 class="mb-0"></h4>
      </div>
      <div class="inv-card w-30 p-4 m-3">
        <h4 class="mb-0">Twitterでシェア</h4>
      </div>
      <div class="inv-card w-30 p-4 m-3">
        <h4 class="mb-0">URLを発行する</h4>
      </div>
    </div>
  </div>
</main>