config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root "root#top"

  get  "signup" => "users#new"
  post  "signup" => "users#create"
  get "tos" => "users#tos", as: :tos
  get "send_email" => "users#send_email", as: :send_email
  get "mypage/:user_id" => "users#show", as: :mypage
  get "wedding_gift/:user_id" => "users#wedding_gift", as: :wedding_gift
  resources :users, only: [:edit, :update, :destroy]

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :password_resets, only: [:new, :create, :edit, :update]

  get ":user_id/invitations/type" => "invitations#type", as: :type
  get "invitations/:id/profile" => "invitations#profile", as: :profile
  get "invitations/:id/date_place" => "invitations#date_place", as: :date_place
  get "invitations/:id/greeting" => "invitations#greeting", as: :greeting
  get "invitations/:id/preview/:design_id" => "invitations#preview", as: :preview
  get ":user_id/invitations/couple_name/:type_id" => "invitations#couple_name", as: :couple_name
  get "invitations/design/:id/:type_id" => "invitations#design", as: :design
  get "invitations/:user_id/index" => "invitations#index", as: :index
  resources :invitations, only: [:show, :update, :create, :destroy]

  get "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#show", as: :attendance_form_show
  patch "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#update", as: :attendance_form_update

  get "attendances/:atd_id/confirm" => "attendances#confirm", as: :confirm
  resources :attendances, only: [:show, :create, :update]

  get "lists/:user_id" => "lists#show", as: :list

  resources :account_activations, only: [:edit]

  get "message_cards/:id/profile" => "message_cards#profile", as: :msg_profile
  get "message_cards/:id/preview" => "message_cards#preview", as: :msg_preview
  get "message_cards/:id/greeting" => "message_cards#greeting", as: :msg_greeting
  get "message_cards/:user_id/index" => "message_cards#index", as: :msg_index
  resources :message_cards, only: [:new, :show, :update, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :invitations
  has_many :message_cards
  has_many :attendances
  has_many :attendance_forms


  def self.from_omniauth(auth)
    user = User.where('email = ?', auth.info.email).first
    if user.blank?
      user = User.new
    end
    user.uid   = auth.uid
    user.provider = auth.provider
    user.name  = auth.info.name
    user.email = auth.info.email
    user.user_image  = URI.parse(auth.info.image)
    user.password = User.new_token
    user.password_confirmation = user.password
    user
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def activate
    update_attribute(:activated, true)
    update_attribute(:activated_at, Time.zone.now)
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_attribute(:reset_digest, User.digest(reset_token))
    update_attribute(:reset_sent_at, Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def receive_notification
    MessageMailer.receive_notification(self).deliver_now
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
        self.activation_token  = User.new_token
        self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def show
    @user = current_user
    @invitation = Invitation.find_by(user_id: params[:user_id])
    @message_card = MessageCard.new
  end

  def create
    @user = User.new(user_params)
      if @user.save
        @user.send_activation_email
        redirect_to send_email_url
      else
        flash[:danger] = "すでに登録されているメールアドレスです。"
        render "new"
      end
  end

  def wedding_gift
  end

  def tos
  end

  def send_email
  end

  private

    def user_params
      params.require(:user).permit(
        :name, :email, :password, :password_confirmation,
        :user_image, :provider, :uid,
      )
    end

    def correct_user
      @user = User.find_by(id: params[:id])
      redirect_to root_url unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def ensure_correct_user
    if current_user.id != params[:user_id].to_i
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

  def ensure_inv_correct_user
    @invitation = Invitation.find_by(id: params[:id])
    if current_user.id != @invitation.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

  def ensure_msg_card_correct_user
    @msg_card = MessageCard.find_by(id: params[:id])
    if current_user.id != @msg_card.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

  def ensure_atd_correct_user
    @attendance = Attendance.find_by(id: params[:id])
    if current_user.id != @attendance.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

  def ensure_atdform_correct_user
    @invitation = Invitation.find_by(id: params[:id])
    if current_user.id != @invitation.user_id
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end

  def ensure_list_correct_user
    if current_user.id != params[:user_id].to_i
      flash[:danger] = "権限がありません"
      redirect_to root_url
    end
  end
end

app/views/users/money.html.erb
<% provide(:title, "決済管理") %>
  <!-- ========== MAIN ========== -->
  <main id="content" role="main" class="" style="">
    <div class="container text-center">
      <h2>決済管理</h2>
      <div class="type text-left">
        <h3 class="mb-4" style="margin-left:15%;">挙式・披露宴</h3>
        <div class="row w-80" style="margin-left:20%;">
          <div class="col-sm-6">
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">出席<span class="ml-9">60名</span></p>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">欠席<span class="ml-9">8名</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">名簿一覧</a>
            </div>
          </div>
          <div class="col-sm-6">
            <label class="mt-6">ご祝儀</label>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style=""><span class="ml-9">¥100,000</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">一覧</a>
            </div>
          </div>
        </div>
      </div>


      <div id="money" class="type text-left" style="margin-top:100px;">
        <h3 class="mb-4" style="margin-left:15%;">二次会・パーティー</h3>
        <div class="row w-80" style="margin-left:20%;">
          <div class="col-sm-6">
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">出席<span class="ml-9">60名</span></p>
            <p class="btn-primary rounded-pill w-50 py-3 px-4">欠席<span class="ml-9">7名</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">名簿一覧</a>
            </div>
          </div>
          <div class="col-sm-6">
            <label class="mt-6">会費</label>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style=""><span class="ml-9">¥100,000</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">一覧</a>
            </div>
          </div>
        </div>
      </div>

      <div class="mt-9">
        <%= link_to "戻る", users_path(id: @user), class:"btn btn-sm btn-secondary pl-8 pr-8 mt-4" %>
      </div>
    </div>
  </main>

app/views/users/new.html.erb
<% provide(:title, "新規登録") %>

<%= form_for(@user, url: signup_path) do |f| %>
  <!-- ========== MAIN ========== -->
  <main id="content" role="main" class="" style="">
    <div id="signup" class="container text-center">

      <div class="my-4">
        <h1>新規登録</h1>
      </div>
    <!-- Input -->
      <div class="mb-4">
        <div class="u-form w-50 mx-auto text-primary" style="">
          <%= f.label :email, "メールアドレス", class:"d-block small text-left" %>
          <%= f.email_field :email, placeholder:"info@example.com", class:"w-100 p-2" %>
        </div>
      </div>
    <!-- End Input -->

    <!-- Input -->
      <div class="mb-4">
        <div class="u-form w-50 mx-auto text-primary" style="">
          <%= f.label :password, "パスワード", class:"d-block small text-left" %>
          <%= f.password_field :password, placeholder:"英数字8文字以上", class:"w-100 p-2" %>
        </div>
      </div>
    <!-- End Input -->

    <!-- Input -->
      <div class="mb-4">
        <div class="u-form w-50 mx-auto text-primary" style="">
        <%= f.label :password_confirmation, "パスワード(確認)", class:"d-block small text-left" %>
        <%= f.password_field :password_confirmation, placeholder:"英数字8文字以上", class:"w-100 p-2" %>
        </div>
      </div>
    <!-- End Input -->

    <!-- Checkbox -->
      <div class="js-form-message mb-5">
        <div class="custom-control custom-checkbox d-flex align-items-center text-muted w-50 mx-auto" style="">
          <input type="checkbox" class="custom-control-input" id="termsCheckbox" name="termsCheckbox" required
                   data-msg="Please accept our Terms and Conditions."
                   data-error-class="u-has-error"
                   data-success-class="u-has-success">
          <label class="custom-control-label" for="termsCheckbox">
            <small>
              <%= link_to "利用規約", tos_path %>に同意する。
            </small>
          </label>
        </div>
      </div>
        <!-- End Checkbox -->

      <%= f.submit "登録する", class:"btn btn-sm btn-primary pl-7 pr-7" %>
    </div>
  </main>
<% end %>

app/views/users/payment.html.erb
<% provide(:title, "受取会費確認") %>

<%= render 'shared/error_messages', model: @user %>
  <!-- ========== MAIN ========== -->
  <main id="content" role="main" class="" style="">
    <div class="container text-center">
      <h2>受取会費確認</h2>
      <div class="type text-left">
        <h3 class="mb-4" style="margin-left:15%;">挙式・披露宴</h3>
        <div class="row w-80" style="margin-left:20%;">
          <div class="col-sm-6">
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">出席<span class="ml-9">60名</span></p>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">欠席<span class="ml-9">8名</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">名簿一覧</a>
            </div>
          </div>
          <div class="col-sm-6">
            <label class="mt-6">ご祝儀</label>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style=""><span class="ml-9">¥100,000</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">一覧</a>
            </div>
          </div>
        </div>
      </div>


      <div id="money" class="type text-left" style="margin-top:100px;">
        <h3 class="mb-4" style="margin-left:15%;">二次会・パーティー</h3>
        <div class="row w-80" style="margin-left:20%;">
          <div class="col-sm-6">
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">出席<span class="ml-9">60名</span></p>
            <p class="btn-primary rounded-pill w-50 py-3 px-4">欠席<span class="ml-9">7名</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">名簿一覧</a>
            </div>
          </div>
          <div class="col-sm-6">
            <label class="mt-6">会費</label>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style=""><span class="ml-9">¥100,000</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">一覧</a>
            </div>
          </div>
        </div>
      </div>

      <div class="mt-9">
        <%= link_to "戻る", users_path(id: @user), class:"btn btn-sm btn-secondary pl-8 pr-8 mt-4" %>
      </div>
    </div>
  </main>

app/views/users/send_email.html.erb
<%= form_for(:session, url: login_path) do |f| %>

<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
  <!-- Input -->
    <div class="text-dark mt-9">
      <h4 class="mb-4">
        登録メールアドレスに本登録のURLを送信しました。<br>
        現在仮登録ですので本登録を済ませください。
      </h4>
      <h6 class="small">
        ※メールが届かない場合、迷惑メールに分類されているか、ドメイン指定受信が許可されていない場合があります。<br>
        その場合は「@○○○.com」のドメイン指定受信設定を行って下さい。
      </h6>
    </div>
  </div>
</main>
<% end %>

app/views/users/show.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="mx-auto"  style="max-width:1200px;">
  <div class="text-center">
    <div class="overflow-hidden">
      <div class="col-sm-6 float-left">
        <div class="p-4 my-auto align-middle">
          <img src="/default.jpg" width="" class="w-80">
        </div>
      </div>
      <div class="col-sm-3 float-left text-left pl-0">
        <h2 class="mt-8">新郎名 & 新婦名</h2>
        2019/1/19<br>
        あと何日（カウントダウン日にち）
      </div>
      <div class="col-sm-3 float-left text-left pl-0">
        <h4 class="mt-4 mb-2">現在の招待状回答率</h4>
        <div class="js-hr-progress progress m-4" style="height: 25px;">
          <div class="js-hr-progress-bar progress-bar bg-gold" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"><span class="" style="font-size: 150%;">80%</span></div>
        </div>
        <h4 class="mt-8 mb-2">招待状回答状況</h4>
        <ul class="text-left" style="">
          <li class="">出席：23人</li>
          <li class="">欠席：3人</li>
          <li class="">未回答：120人</li>
        </ul>
      </div>
        <!-- <div class="" style="border:3px solid gray;">
          <ul class="row" style="margin:0 15px !important;">
            <li class="col">出席：23人</li>
            <li class="col">欠席：3人</li>
            <li class="col">未回答：120人</li>
          </ul>
          <div class="js-hr-progress progress m-4" style="height: 25px;">
            <div class="js-hr-progress-bar progress-bar bg-warning" role="progressbar" style="width: 80%;" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"><span class="" style="font-size: 150%;">80%</span></div>
          </div>
          <ul class="w-70" style="margin-left:30%;">
            <li class="row text-right mx-4" style="">
              <h3 class="w-100 mb-0">現在金額　¥1,000,000</h3>
            </li>
            <li class="row text-right mx-4" style="">
              <h3 class="w-100 mb-0 text-primary">目標金額　¥1,000,000</h3>
            </li>
          </ul>
        </div> -->

        <!-- <div class="row mt-8">
          <div class="col-6">
            <div class="btn btn-lg btn-primary btn-outline-primary w-80">人数</div>
          </div>
          <div class="col-6">
            <div class="btn btn-lg btn-primary btn-outline-primary w-80">金額</div>
          </div>
        </div> -->
      </div>
    </div>
  </div>
  <div class="text-center mx-auto">
    <div class=" overflow-hidden">
      <div class="col-md-3 col-sm-4 col-xs-6 float-left">
        <% if Invitation.find_by(user_id: current_user) %>
        <%= link_to index_path(user_id: params[:user_id]) do  %>
          <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
            <img src="/mypage/message.png" width="" class="w-100  step-icon">
            <img src="/mypage/message2.png" width="" class="w-100  step-icon-hover">
            <p class="">招待状一覧</p>
          </div>
        <% end %>
      <% else %>
        <%= link_to type_path do  %>
        <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
          <img src="/mypage/message.png" width="" class="w-100  step-icon">
          <img src="/mypage/message2.png" width="" class="w-100  step-icon-hover">
          <p class="">招待状新規作成</p>
        </div>
        <% end %>
      <% end %>

      </div>
      <div class="col-md-3 col-sm-4 col-xs-6 float-left">
        <% if MessageCard.find_by(user_id: current_user) %>
          <%= link_to msg_index_path(user_id: params[:user_id]) do  %>
            <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
              <img src="/mypage/card.png" width="" class="w-100  step-icon">
              <img src="/mypage/card2.png" width="" class="w-100  step-icon-hover">
              <p class="">メッセージカード一覧</p>
            </div>
          <% end %>
        <% else %>
          <%= link_to new_message_card_path do  %>
          <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
            <img src="/mypage/card.png" width="" class="w-100  step-icon">
            <img src="/mypage/card2.png" width="" class="w-100  step-icon-hover">
            <p class="">メッセージカード新規作成</p>
          </div>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-3 col-sm-4 col-xs-6 float-left">
        <%= link_to wedding_gift_path do  %>
        <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
          <img src="/mypage/bank.png" width="" class="w-100  step-icon">
          <img src="/mypage/bank2.png" width="" class="w-100  step-icon-hover">
          <p class="">受取会費確認</p>
        </div>
        <% end %>
      </div>
      <div class="col-md-3 col-sm-4 col-xs-6 float-left">
        <%= link_to list_path(user_id: params[:user_id]) do  %>
        <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
          <img src="/mypage/meibo.png" width="" class="w-100  step-icon">
          <img src="/mypage/meibo2.png" width="" class="w-100  step-icon-hover">
          <p class="">名簿管理</p>
        </div>
        <% end %>
      </div>

      <div class="col-md-3 col-sm-4 col-xs-6 float-left">
        <%= link_to couple_name_path(type_id: 1) do  %>
        <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
          <img src="/mypage/camera.png" width="" class="w-100  step-icon">
          <img src="/mypage/camera2.png" width="" class="w-100  step-icon-hover">
          <p class="">写真管理</p>
        </div>
        <% end %>
      </div>
      <div class="col-md-3 col-sm-4 col-xs-6 float-left">
        <%= link_to couple_name_path(type_id: 2) do  %>
        <div class="step-card w-100 mypage-card p-4 m-6 mx-auto ">
          <img src="/mypage/goshugi-bukuro.png" width="" class="w-100  step-icon">
          <img src="/mypage/goshugi-bukuro2.png" width="" class="w-100  step-icon-hover">
          <p class="">オプションサービス</p>
        </div>
        <% end %>
        </div>
      <!-- <div class="col-md-3 col-sm-4 col-xs-6">
        <%= link_to couple_name_path(type_id: 3) do  %>
        <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
          <img src="/step_icon/3.png" width="" class="w-50 ">
          <p class="">？？？</p>
        </div>
        <% end %>
      </div>
      <div class="col-md-3 col-sm-4 col-xs-6">
        <%= link_to couple_name_path(type_id: 4) do  %>
        <div class="step-card w-100 mypage-card p-4 m-6 mx-auto">
          <img src="/step_icon/4.png" width="" class="w-50 ">
          <p class="">？？？</p>
        </div>
        <% end %>
      </div> -->
    </div>

  </div>
</main>

app/views/users/tos.html.erb
利用規約

app/views/users/wedding_gift.html.erb
<% provide(:title, "受取会費確認") %>
  <!-- ========== MAIN ========== -->
  <main id="content" role="main" class="" style="">
    <div class="container text-center">
      <h2>受取会費確認</h2>
      <div class="type text-left">
        <h3 class="mb-4" style="margin-left:15%;">挙式・披露宴</h3>
        <div class="row w-80" style="margin-left:20%;">
          <div class="col-sm-6">
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">出席<span class="ml-9">60名</span></p>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">欠席<span class="ml-9">8名</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">名簿一覧</a>
            </div>
          </div>
          <div class="col-sm-6">
            <label class="mt-6">ご祝儀</label>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style=""><span class="ml-9">¥100,000</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">一覧</a>
            </div>
          </div>
        </div>
      </div>


      <div id="money" class="type text-left" style="margin-top:100px;">
        <h3 class="mb-4" style="margin-left:15%;">二次会・パーティー</h3>
        <div class="row w-80" style="margin-left:20%;">
          <div class="col-sm-6">
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style="">出席<span class="ml-9">60名</span></p>
            <p class="btn-primary rounded-pill w-50 py-3 px-4">欠席<span class="ml-9">7名</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">名簿一覧</a>
            </div>
          </div>
          <div class="col-sm-6">
            <label class="mt-6">会費</label>
            <p class="btn-primary rounded-pill w-50 py-3 px-4" style=""><span class="ml-9">¥100,000</span></p>
            <div class="text-center">
              <a class="btn btn-outline-primary text-primary">一覧</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>