config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root "root#top"

  get  "signup" => "users#new"
  post  "signup" => "users#create"
  get "tos" => "users#tos", as: :tos
  get "send_email" => "users#send_email", as: :send_email
  get "mypage/:user_id" => "users#show", as: :mypage
  get "wedding_gift/:user_id" => "users#wedding_gift", as: :wedding_gift
  resources :users, only: [:edit, :update, :destroy]

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :password_resets, only: [:new, :create, :edit, :update]

  get ":user_id/invitations/type" => "invitations#type", as: :type
  get "invitations/:id/profile" => "invitations#profile", as: :profile
  get "invitations/:id/date_place" => "invitations#date_place", as: :date_place
  get "invitations/:id/greeting" => "invitations#greeting", as: :greeting
  get "invitations/:id/preview/:design_id" => "invitations#preview", as: :preview
  get ":user_id/invitations/couple_name/:type_id" => "invitations#couple_name", as: :couple_name
  get "invitations/design/:id/:type_id" => "invitations#design", as: :design
  get "invitations/:user_id/index" => "invitations#index", as: :index
  resources :invitations, only: [:show, :update, :create, :destroy]

  get "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#show", as: :attendance_form_show
  patch "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#update", as: :attendance_form_update

  get "attendances/:atd_id/confirm" => "attendances#confirm", as: :confirm
  resources :attendances, only: [:show, :create, :update]

  get "lists/:user_id" => "lists#show", as: :list

  resources :account_activations, only: [:edit]

  get "message_cards/:id/profile" => "message_cards#profile", as: :msg_profile
  get "message_cards/:id/preview" => "message_cards#preview", as: :msg_preview
  get "message_cards/:id/greeting" => "message_cards#greeting", as: :msg_greeting
  get "message_cards/:user_id/index" => "message_cards#index", as: :msg_index
  resources :message_cards, only: [:new, :show, :update, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  has_many :attendance_forms
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :logged_in_user
  before_action :ensure_correct_user, only: [:index, :couple_name, :type]
  before_action :ensure_inv_correct_user, except: [:index, :couple_name, :type, :preview, :create, :update]

  def start
    @invitation = Invitation.find_by(id: params[:id])
  end

  def index
    @invitations = Invitation.where(user_id: params[:user_id]).order("created_at ASC")
  end

  def type
    @invitation = Invitation.find_by(id: params[:id])
  end

  def couple_name
    @invitation = Invitation.new
    @attendance_form = AttendanceForm.new
  end

  def design
    @invitation = Invitation.find_by(id: params[:id])
  end

  def profile
    @invitation = Invitation.find_by(id: params[:id])
  end

  def date_place
    @invitation = Invitation.find_by(id: params[:id])
  end

  def greeting
    @invitation = Invitation.find_by(id: params[:id])
  end

  def preview
    @attendance = Attendance.new
    @invitation = Invitation.find_by(id: params[:id])
    if @invitation.design_id == 1
      render "preview1"
    elsif @invitation.design_id == 2
      render "preview2"
    elsif @invitation.design_id == 3
      render "preview3"
    elsif @invitation.design_id == 4
      render "preview4"
    end
  end

  def show
    @invitation = Invitation.find_by(id: params[:id])
    @attendance_form = AttendanceForm.find_by(invitation_id: params[:id])
    @url = request.url
    @url_encode = CGI.escape(@url)
  end

  def create
    @invitation = current_user.invitations.new(invitation_params)
    @attendance_form = @invitation.attendance_forms.new(attendance_form_params)

    if @invitation.save && @attendance_form.save
      redirect_to design_url(user_id: current_user, type_id: @invitation, id: @invitation)
    else
      render "couple_name"
    end
  end

  def update
    @invitation = Invitation.find_by(id: params[:id])
    @attendance_form = AttendanceForm.find_by(invitation_id: params[:id])
    if @invitation.update_attributes(invitation_params) && @attendance_form.update_attributes(user_id: current_user.id)
      redirect_to invitation_url(@invitation)
    else
      render "design"
    end
  end

  private

    def invitation_params
      params.require(:invitation).permit(
        :type_id, :design_id, :title, :greeting, :public,
        :groom_last, :groom_first, :groom_last_kana, :groom_first_kana, :groom_msg,
        :bride_last, :bride_first, :bride_last_kana, :bride_first_kana, :bride_msg,
        :date1, :opentime1, :starttime1, :place1, :address1, :phonenumber1, :place_url1, :note1,
        :date2, :opentime2, :starttime2, :place2, :address2, :phonenumber2, :place_url2, :note2,
        attendance_form_attributes: [:user_id, :invitation_id, :type_id]
      )
    end

    def attendance_form_params
      params.require(:invitation).permit(
        :user_id, :invitation_id, :type_id
      )
    end
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/views/invitations/attendance.html.erb
<%= link_to "招待状編集TOPへ", invitation_path(id: @invitation) %>

<%= form_for(@invitation, url: invitation_path, method: "PATCH") do |f| %>
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="row">
      <div class="text-center">
        <h2 class="mb-0" style="">出欠フォーム編集</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
      </div>
      <div class="col-4"></div>
    </div>

    <div class="inv-date_place">
      <div class="row mt-4">
        <div class="col-sm-4">
          <p class="text-primary"><%= f.label "回答期限" %></p>
        </div>
        <div class="text-left col-sm-8">
          <div class="" style="">
            <%= f.text_field :date1, class:"w-80 p-2",id:"date_sample" %>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="defaultCheck_expire">
              <label class="form-check-label" for="defaultCheck_expire">
                回答期限を設定しない
              </label>
            </div>
          </div>
        </div>
      </div>


      <div class="row mt-4">
        <div class="col-sm-4">
          <p class="text-primary"><%= f.label "フォーム用挨拶文" %></p>
        </div>
        <div class="text-left col-sm-8">
          <div class="" style="">
            <%= f.text_field :address1, value:"お手数ではございますが、出席情報のご記入をお願い申し上げます。", class:"w-80 p-2" %><!-- 送り先を編集してください！！！ to_立花さん -->
          </div>
        </div>
      </div>

      <div class="row mt-4">
        <div class="col-sm-4">
          <p class="text-primary mb-0"><%= f.label "フォーム回答項目",class:"mb-0" %></p>
        </div>
        <div class="text-left col-sm-8">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_name">
                  <label class="form-check-label" for="defaultCheck_name">
                    お名前
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_name" id="exampleRadios_name_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_name_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_name" id="exampleRadios_name_2" value="">
                  <label class="form-check-label" for="exampleRadios_name_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_name_read">
                  <label class="form-check-label" for="defaultCheck_name_read">
                    かな
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_name_read" id="exampleRadios_name_read_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_name_read_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_name_read" id="exampleRadios_name_read_2" value="">
                  <label class="form-check-label" for="exampleRadios_name_read_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_post">
                  <label class="form-check-label" for="defaultCheck_post">
                    郵便番号
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_post" id="exampleRadios_post_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_post_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_post" id="exampleRadios_post_2" value="">
                  <label class="form-check-label" for="exampleRadios_post_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_address">
                  <label class="form-check-label" for="defaultCheck_address">
                    住所
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_address" id="exampleRadios_address_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_address_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_address" id="exampleRadios_address_2" value="">
                  <label class="form-check-label" for="exampleRadios_address_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_building">
                  <label class="form-check-label" for="defaultCheck_building">
                    建物名
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_building" id="exampleRadios_building_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_building_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_building" id="exampleRadios_building_2" value="">
                  <label class="form-check-label" for="exampleRadios_building_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_tel">
                  <label class="form-check-label" for="defaultCheck_tel">
                    電話番号
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_tel" id="exampleRadios_tel_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_tel_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_tel" id="exampleRadios_tel_2" value="">
                  <label class="form-check-label" for="exampleRadios_tel_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_email">
                  <label class="form-check-label" for="defaultCheck_email">
                    メールアドレス
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_email" id="exampleRadios_email_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_email_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_email" id="exampleRadios_email_2" value="">
                  <label class="form-check-label" for="exampleRadios_email_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_allergy">
                  <label class="form-check-label" for="defaultCheck_allergy">
                    アレルギー
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_allergy" id="exampleRadios_allergy_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_allergy_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_allergy" id="exampleRadios_allergy_2" value="">
                  <label class="form-check-label" for="exampleRadios_allergy_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-sm-4">
        </div>
        <div class="text-left col-sm-8 mt-2">
          <div class="" style="">
            <div class="row">
              <div class="col-sm-4">
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" value="" id="defaultCheck_message">
                  <label class="form-check-label" for="defaultCheck_message">
                    メッセージ
                  </label>
                </div>
              </div>
              <div class="col-sm-8 row">
                <div class="form-check mr-4">
                  <input class="form-check-input" type="radio" name="exampleRadios_message" id="exampleRadios_message_1" value="" checked>
                  <label class="form-check-label" for="exampleRadios_message_1">
                    必須にする
                  </label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="radio" name="exampleRadios_message" id="exampleRadios_message_2" value="">
                  <label class="form-check-label" for="exampleRadios_message_2">
                    必須にしない
                  </label>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

    <div class="mt-9">
      <%= f.submit "保存", class:"btn btn-sm btn-primary pl-8 pr-8" %><br>
      <%= link_to "戻る", invitation_path(id: @invitation), class:"btn btn-sm btn-secondary pl-8 pr-8 mt-4" %>
    </div>

  </div>
</main>


<!-- bootstrap-datepickerのjavascriptコード -->
<script>
    $('#date_sample').datepicker({
        language:'ja',
        format: 'yyyy/mm/dd'
    });
</script>


<% end %>

app/views/invitations/couple_name.html.erb
<%= form_for(@invitation, url: invitations_path) do |f| %>
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div id="couple_name" class="container text-center">
    <div class="row">
      <div class="col-4">
        <h2 class="" style="">STEP1</h2>
      </div>
      <div class="col-4">
        <h2 class="mb-0">STEP2</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-20"></div>
        <p class="">お名前の入力</p>
      </div>
      <div class="col-4">
        <h2 class="">STEP3</h2>
      </div>
    </div>

    <div class="text-left text-primary">
      <div class="row">
        <div class="col-2"></div>
        <div class="col-4">
          <%= f.label "新婦", class:"d-block font-weight-bold" %>
          <div class="u-form w-100 mx-auto text-primary">
            <%= f.text_field :groom_last,placeholder:"姓（Last Name）", class:"" %>
          </div>
        </div>
        <div class="col-4">
          <%= f.label "新婦", class:"d-block font-weight-bold text-transparent" %>
          <div class="u-form w-100 mx-auto text-primary">
            <%= f.text_field :groom_first,placeholder:"名（First Name）", class:"" %>
          </div>
        </div>
      </div>
    </div>
    <div class="text-left mt-6 text-primary">
      <div class="row">
        <div class="col-2"></div>
        <div class="col-4">
          <%= f.label "新婦", class:"d-block font-weight-bold" %>
          <div class="u-form w-100 mx-auto text-primary">
            <%= f.text_field :bride_last,placeholder:"姓（Last Name）", class:"" %>
          </div>
        </div>
        <div class="col-4">
          <%= f.label "新婦", class:"d-block font-weight-bold text-transparent" %>
          <div class="u-form w-100 mx-auto text-primary">
            <%= f.text_field :bride_first,placeholder:"名（First Name）", class:"" %>
          </div>
        </div>
      </div>
    </div>
      <%= f.hidden_field :type_id, value: params[:type_id] %>
    <div class="mt-8">
      <%= f.fields_for(@attendance_form) do |atdf| %>
        <%= atdf.hidden_field :user_id, value: current_user.id %>
        <%= atdf.hidden_field :type_id, value: params[:type_id] %>
      <%= f.submit "OK", class:"btn btn-sm btn-primary pl-8 pr-8" %>
      <% end %>
    </div>
  </div>
</main>
<% end %>

app/views/invitations/index.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="">
      <div class="text-center">
        <h2 class="mb-0" style="">招待状一覧</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
      </div>
    </div>
    <div class="row">
      <% @invitations.each do |inv| %>
      <div class="col-3">
        <%= link_to invitation_path(id: inv.id) do %>
        <div class="m-4 mx-auto">
          <img src="/default.jpg" width="" class="w-80 mt-4">
          <p class="mt-4"><%= inv.id %></p>
        </div>
      </div>
      <% end %>
      <% end %>
      <div class="col-3">
        <%= link_to type_path do %>
        <div class="step-card invitations p-4 m-6 mx-auto">
          <img src="/mypage/card.png" width="" class="w-100  step-icon">
          <img src="/mypage/card2.png" width="" class="w-100  step-icon-hover">
          <p class="">新規作成</p>
        </div>
        <% end %>
      </div>
    </div>
    <div>
    </div>
  </div>
</main>

app/views/invitations/show.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center w-60">
    <div class="">
      <div class="text-center">
        <h2 class="mb-0" style="">招待状編集TOP</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
        <h6 class="mt-8">
          <% if @invitation.title.nil? %>
          <div class="">
            <p>
              招待状_<%= @invitation.id %>
              <!-- 切り替えボタンの設定 -->
              <a type="" class="yubi" data-toggle="modal" data-target="#exampleModalCenter">
                <img src="/icon/pencil.png" class="w-5 p-2">
              </a>
            </p>
          </div>
          <% else %>
          <div class="">
            <p>
              <%= @invitation.title %>
              <!-- 切り替えボタンの設定 -->
              <a type="" class="yubi" data-toggle="modal" data-target="#exampleModalCenter">
                <img src="/icon/pencil.png" class="w-5 p-2">
              </a>
            </p>
          </div>
          <% end %>
        </h6>

        <!-- モーダルの設定 -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title w-100" id="exampleModalCenterTitle">招待状の名前を変更する</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <%= form_for(@invitation, url: invitation_path, method: "PATCH") do |f| %>
                <% if @invitation.title.nil? %>
                <div class="modal-body">
                  <p><%= f.text_field :title, value: "招待状_#{@invitation.id}" %></p>
                </div>
                <% else %>
                <div class="modal-body">
                  <p><%= f.text_field :title, value: @invitation.title %></p>
                </div>
                <% end %>
                <div class="modal-footer">
                  <%= f.submit "変更を保存", class: "btn btn-sm btn-primary" %>
                  <button type="button" class="btn btn-sm btn-dark" data-dismiss="modal">閉じる</button>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="my-4 text-center">
      <% if @invitation.public == false %>
        <%= link_to invitation_path(@invitation, :invitation => {public: true}), method: "PATCH", class:"btn btn-sm btn-primary pl-8 pr-8" do %>
          公開
        <% end %>
      <% else %>
        <%= link_to invitation_path(@invitation, :invitation => {public: false}), method: "PATCH", class:"btn btn-sm btn-primary pl-8 pr-8" do %>
          非公開
        <% end %>
      <% end %>
    </div>
    <div class="mt-4 bg-img img-fit">
      <%= link_to design_path(id: @invitation, type_id: @invitation.type_id),class:"bg-img-padding w-100 my-auto" do %>
      <div class="amikake" style="height: 300px;background-color: rgba(0,0,0,.5);">
        <p class="text-white" style="padding-top:140px;">画像を選択する</p>
      </div>
    </div>
    <% end %>
    <div class="mt-4 m-0" style="overflow:hidden;">
      <%= link_to profile_path(id: @invitation) do %>

      <div class="inv-card w-49 p-4" style="float:left;">
        <h4 class="mb-0">プロフィール</h4>
      </div>
      <% end %>

      <%= link_to date_place_path(id: @invitation) do %>
      <div class="inv-card w-49 p-4" style="float:right;">
        <h4 class="mb-0">会場・日付</h4>
      </div>
      <% end %>
    </div>

    <div class="mt-4 m-0">
      <%= link_to greeting_path(id: @invitation) do %>
      <div class="inv-card w-49 p-4" style="float:left;">
        <h4 class="mb-0">挨拶文</h4>
      </div>
      <% end %>

      <%= link_to attendance_form_show_path(id: params[:id], atdform_id: @attendance_form) do %>
      <div class="inv-card w-49 p-4" style="float:right;">
        <h4 class="mb-0">出欠フォーム</h4>
      </div>
      <% end %>
    </div>
    <div>
      <%= link_to "プレビュー", preview_path(id: @invitation, design_id: @invitation.design_id), class:"btn btn-sm btn-primary pl-8 pr-8 mb-2 mt-4" %><br>
    </div>
    <div class="w-80 mt-4 m-0 overflow-hidden" style="margin-left:10% !important;">
      <div class="inv-card w-49 p-4 float-left">
        <%= link_to "https://social-plugins.line.me/lineit/share?url=#{@url}" do %>
          <h4 class="mb-0">LINEで送る</h4>
        <% end %>
      </div>
      <!-- <div class="inv-card w-49 p-4 float-right">
        <%= link_to "http://www.facebook.com/share.php?u=#{@url}" do %>
          <h4 class="mb-0">FBでシェア</h4>
        <% end %>
      </div>
    </div>
    <div class="w-80 mt-4 m-0 overflow-hidden" style="margin-left:10% !important;">
      <div class="inv-card w-49 p-4 float-left">
        <%= link_to "http://twitter.com/share?url=#{@url}" do %>
          <h4 class="mb-0">Twitterでシェア</h4>
        <% end %>
      </div> -->
      <div class="inv-card w-49 p-4 float-right">
        <!-- コピー対象要素とコピーボタン -->
        <input id="copyTarget" type="text" value="<%= @url %>" readonly class="invisible p-0 m-0" style="height:0; width: 0;border:none;">
        <a onclick="copyToClipboard()" class="h4 yubi">URLをコピー</a>
      </div>

    </div>
  </div>
</main>


    <!-- テキストをコピーするjs -->
    <script>
        function copyToClipboard() {
            // コピー対象をJavaScript上で変数として定義する
            var copyTarget = document.getElementById("copyTarget");
            // コピー対象のテキストを選択する
            copyTarget.select();
            // 選択しているテキストをクリップボードにコピーする
            document.execCommand("Copy");
            // コピーをお知らせする
            alert("コピーできました！ : " + copyTarget.value);
        }
    </script>

app/views/invitations/type.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" class="" style="">
  <div class="container text-center">
    <div class="row">
      <div class="col-4">
        <h2 class="mb-0" style="">STEP1</h2>
        <div class="mb-3 text-center" style=""><img src="/icon/bar.png" class="w-10"></div>
        <p class="">イベント形式の選択</p>
      </div>
      <div class="col-4">
        <h2 class="">STEP2</h2>
      </div>
      <div class="col-4">
        <h2 class="">STEP3</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-sm-6 ">
        <%= link_to couple_name_path(type_id: 1) do  %>
          <div class="step-card p-4 m-6 mx-auto">
            <img src="/step_icon/couple.png" width="" class="w-100 mt-4 step-icon">
            <img src="/step_icon/couple-blue.png" width="" class="w-100 mt-4 step-icon-hover">
            <p class="mt-4">挙式・披露宴</p>
          </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-sm-6 ">
        <%= link_to couple_name_path(type_id: 2) do  %>
          <div class="step-card p-4 m-6 mx-auto">
            <img src="/step_icon/flower.png" width="" class="w-100 mt-4 step-icon">
            <img src="/step_icon/flower-blue.png" width="" class="w-100 mt-4 step-icon-hover">
            <p class="mt-4">挙式のみ</p>
          </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-sm-6 ">
        <%= link_to couple_name_path(type_id: 3) do  %>
          <div class="step-card p-4 m-6 mx-auto">
            <img src="/step_icon/cake.png" width="" class="w-100 mt-4 step-icon">
            <img src="/step_icon/cake-blue.png" width="" class="w-100 mt-4 step-icon-hover">
            <p class="mt-4">披露宴のみ</p>
          </div>
        <% end %>
      </div>
      <div class="col-lg-3 col-sm-6 ">
        <%= link_to couple_name_path(type_id: 4) do  %>
          <div class="step-card p-4 m-6 mx-auto">
            <img src="/step_icon/champagne.png" width="" class="w-100 mt-4 step-icon">
            <img src="/step_icon/champagne-blue.png" width="" class="w-100 mt-4 step-icon-hover">
            <p class="mt-4">二次会</p>
          </div>
        <% end %>
      </div>
    </div>
    <div>
      <%= link_to "SKIP", mypage_path(current_user), class:"btn btn-sm btn-primary pl-8 pr-8 mb-2 mt-4" %><br>
    </div>
  </div>
</main>