config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  root "root#top"

  get  "signup" => "users#new"
  post  "signup" => "users#create"
  get "tos" => "users#tos", as: :tos
  get "send_email" => "users#send_email", as: :send_email
  get "mypage/:user_id" => "users#show", as: :mypage
  get "wedding_gift/:user_id" => "users#wedding_gift", as: :wedding_gift
  resources :users, only: [:edit, :update, :destroy]

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"

  resources :password_resets, only: [:new, :create, :edit, :update]

  get ":user_id/invitations/type" => "invitations#type", as: :type
  get "invitations/:id/profile" => "invitations#profile", as: :profile
  get "invitations/:id/date_place" => "invitations#date_place", as: :date_place
  get "invitations/:id/greeting" => "invitations#greeting", as: :greeting
  get "invitations/:id/preview/:design_id" => "invitations#preview", as: :preview
  get ":user_id/invitations/couple_name/:type_id" => "invitations#couple_name", as: :couple_name
  get "invitations/design/:id/:type_id" => "invitations#design", as: :design
  get "invitations/:user_id/index" => "invitations#index", as: :index
  resources :invitations, only: [:show, :update, :create, :destroy]

  get "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#show", as: :attendance_form_show
  patch "invitations/:id/attendance_form/:atdform_id" => "attendance_forms#update", as: :attendance_form_update

  get "attendances/:atd_id/confirm" => "attendances#confirm", as: :confirm
  resources :attendances, only: [:show, :create, :update]

  get "lists/:user_id" => "lists#show", as: :list

  resources :account_activations, only: [:edit]

  get "message_cards/:id/profile" => "message_cards#profile", as: :msg_profile
  get "message_cards/:id/preview" => "message_cards#preview", as: :msg_preview
  get "message_cards/:id/greeting" => "message_cards#greeting", as: :msg_greeting
  get "message_cards/:user_id/index" => "message_cards#index", as: :msg_index
  resources :message_cards, only: [:new, :show, :update, :create, :destroy]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def top
  end
end

app/helpers/root_helper.rb
module RootHelper
end

app/views/root/top.html.erb
<!-- ========== MAIN ========== -->
<main id="content" role="main" style="">
  <div class="bg-top">
    <div class="top-fv" style="position:relative;">
      <img src="/bg/top-firstview-web.png" class="md-down-hidden">
      <img src="/bg/top-firstview-mobile.png" class="md-up-hidden">
      <div class="top-header w-100" style="position:absolute; top:3%;">
        <div class="row">
          <div class="col-5">
            <div class="">
            </div>
          </div>
          <div class="col-2">
            <div class="logo w-80 mx-auto">
              <img src="/logo/logo.png" class="md-down-hidden">
            </div>
          </div>
          <div class="col-5">
            <div class="type text-center">
              <!-- <a href="#" class="btn btn-lg btn-outline-primary text-gray d-block" style="margin:auto 5% auto 45%;">新郎新婦・幹事様</a>
              <a href="#" class="btn btn-lg btn-outline-primary d-block" style="margin:3% 5% auto 45%;">ご友人・参列者様</a> -->
              <% unless logged_in? %>
                  <%= link_to "無料で招待状をつくる", signup_path, class:"btn btn-sm btn-outline-dark py-1 my-1" %>
                  <%= link_to "ログイン", login_path, class:"btn btn-sm btn-outline-primary py-1 mr-4 my-1" %>
              <% end %>
              <% if logged_in? %>
                <p>ログインユーザー(開発用): <%= current_user.id %></p>
                <%= link_to "マイページ", mypage_path(current_user), class:"btn btn-sm btn-outline-dark py-1" %>
                <%= link_to "ログアウト", logout_path, method: "DELETE", class:"btn btn-sm btn-outline-primary py-1 mr-4" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <!-- <div class="container text-center">
      <div class="row">
        <div class="top-title text-left w-45 align-middle my-auto" style="">
            <h1 class="text-primary font-b font-top">SHUKUFUKU</h1>
            <h3 class="text-primary">
              世界初の「祝い」を目的とした<br>
              クラウドファンディング
            </h3>
            <ul class="sns-icons mt-4" style="margin-left:-10%;">
              <li><img src="/icon/instagram.png" class="w-5"></li>
              <li><img src="/icon/facebook.png" class="w-5 my-4"></li>
              <li><img src="/icon/twitter.png" class="w-5"></li>
            </ul>

        </div>
        <div class="top-img w-50">
          <img src="/top/top-fv.png">
        </div>
      </div>
    </div> -->
      <!-- <div class="d-block" style=""> -->
        <ul class="sns-icons w-50 md-down-hidden" style="position:absolute; bottom:0%; left:5%;">
          <li><img src="/icon/instagram.png" class="w-5"></li>
          <li><img src="/icon/facebook.png" class="w-5 my-4"></li>
          <li><img src="/icon/twitter.png" class="w-5"></li>
        </ul>
      <!-- </div> -->
    </div>
  </div>
  <div class="bg-suggestion text-center">
    <!-- <div class="text-center"> -->
      <h3 class="text-white mb-9">
        ご祝儀袋準備して、ピン札探し回って、当日に大金持ち歩いて<br>
        <span class="" style="font-size:2.5rem">そんな堅苦しい風習、やめちゃいませんか。</span>
      </h3>
    <!-- </div> -->
    <img src="/top/suggestion-human.png" class="w-10">
  </div>

  <div class="bg-point text-center">
    <!-- <div class="text-center"> -->
      <h3 class="text-gray mb-9">
        「祝い」をみんなで作る結婚式クラウドファンディング<span class="text-primary" style="">SHUKUFUKU</span>なら、<br>
        面倒な風習は無くして、誰もが笑顔な結婚式を作れます。
      </h3>
    <!-- </div> -->
    <img src="/top/point-cheer.png" class="w-30">
  </div>

  <div class="merit text-center w-90 mx-auto mt-9" style="">
    <!-- <div class="container"> -->
    <div class="box26">
      <span class="box-title md-down-hidden">電子決済のメリット</span>
      <h2 class="text-primary font-b md-up-hidden">電子決済のメリット</h2>
      <div class="in_box26 m-4 mt-8">
        <div class="row" style="">
          <div class="merit-text col-md-6 text-left align-middle my-auto">
            <img src="/top/merit-1-web.png" class="w-80 mx-auto d-block" style="">
            <h2 class="text-gray mt-4 w-80 mx-auto" style="font-size:24px;">
              事前にご祝儀が受け取れるので、当日の金銭管理の心配もいりません「お金がないから」といってやりたい式を諦めてしまうことも無くなります。
            </h2>
          </div>
          <div class="merit-img col-md-6" style="">
            <img src="/top/merit-img-1.png">
          </div>
        </div>

        <div class="row mt-9 mb-9" style="">
          <div class="merit-text col-md-6 text-left align-middle my-auto">
            <img src="/top/merit-2-web.png" class="w-80 mx-auto d-block" style="">
            <h2 class="text-gray mt-4 w-80 mx-auto" style="font-size:24px;">
              ご祝儀や参列者名簿の電子化により、主催者側の業務が軽減されます。事前に名簿を作る時間や、ご祝儀を受け取る時間が短縮されるので受付がスムーズになります。
            </h2>
          </div>
          <div class="merit-img col-md-6" style="">
            <img src="/top/merit-img-2.png">
          </div>
        </div>

        <div class="row" style="">
          <div class="merit-text col-md-6 text-left align-middle my-auto">
            <img src="/top/merit-3-web.png" class="w-80 mx-auto d-block" style="">
            <h2 class="text-gray mt-4 w-80 mx-auto" style="font-size:24px;">
              クレジットカードなどの電子決済なので、急な出費や友人の結婚の時期が被ってしまった時でも安心です。お金の管理もしやすい他、当日に大金を持ち歩く心配やご祝儀袋を準備する手前もなくなります。
            </h2>
          </div>
          <div class="merit-img col-md-6" style="">
            <img src="/top/merit-img-3.png">
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="bg-service text-center">
    <h2 class="mt-8">他にも、3つの機能が!</h2>
    <!-- <div class="container"> -->
      <div class="row" style="">
        <div class="col-lg-4 my-4">
          <div class="box">
            <img src="/top/service-1.png" class="w-40">
            <h3 class="mt-4">招待状作成</h3>
            <p>好みに合わせてデザインが選べる電子招待状が作成できます。作った招待状はLINEやメールなどで送ることができ、URLを使ってSNS投稿も可能なので、たくさんの友人にご結婚の報告が簡単にできます。</p>
          </div>
        </div>

        <div class="col-lg-4 my-4">
          <div class="box">
            <img src="/top/service-2.png" class="w-40">
            <h3 class="mt-4">出席者リスト</h3>
            <p>今まではExcelなどで作成されていましたが、SHUKUFUKUならゲストの出欠確認、アレルギーなどを一気に管理できます。当日の出席者リストも電子化で簡単に作成可能です。</p>
          </div>
        </div>

        <div class="col-lg-4 my-4">
          <div class="box">
            <img src="/top/service-3.png" class="w-40">
            <h3 class="mt-4">フォトアルバム</h3>
            <p>SHUKUFUKUではゲストが出席した結婚式の写真を、アルバムに投稿し、ゲストや主催者の方々とのシェアや写真の保存が可能です。思い出の写真を共有しませんか?</p>
          </div>
        </div>
      </div>
    <!-- </div> -->
  </div>

  <div class="d-block mx-auto text-center">
    <% unless logged_in? %>
        <%= link_to "利用してみる", signup_path, class:"btn btn-lg btn-outline-primary" %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "利用してみる", mypage_path(current_user), class:"btn btn-lg btn-outline-primary" %>
    <% end %>
  </div>

</main>